#!/bin/sh

host=$1
shift

##
if ! [ -d ~/.sshrdp ] ; then
	mkdir ~/.sshrdp
fi

if [ ! -f ~/.sshrdp/bouncehost ] || [ ! -s ~/.sshrdp/bouncehost ] ; then
	echo "Please put the host you'd like to use for ssh into ~/.sshrdp/bouncehost"
	exit 1
fi

defaultfreerdpopts="-g 1500x980 -d ad -u `whoami` --plugin drdynvc --data tsmf --"
bouncehost=$(cat ~/.sshrdp/bouncehost | head -n 1 | gawk '{print $1}')

usedports=$(netstat --protocol=inet -t -n -a | grep -i listen | gawk '{print $4}' | gawk 'BEGIN{FS=":"}{print $2}' | sort -n)

localport=3389
while echo $usedports | grep -q $localport ; do
	localport=$(($localport+1))
done
echo "Using local port $localport"

## Setup SSH Tunnel

ssh -L $localport:$host:3389 $bouncehost -N &
sshpid=$!
echo "SSH PID: $sshpid"

echo -n "Waiting for ssh tunnel..."
while ! netstat --protocol=inet -t -n -a | grep -i listen | gawk '{print $4}' | gawk 'BEGIN{FS=":"}{print $2}' | grep -q $localport ; do
	sleep 1
done
echo "connected"

## RDP

echo "Connecting to $host via ssh tunnel using xfreerdp" 
xfreerdp --sec nla --certificate-name $host  $defaultfreerdpopts $@ localhost:$localport

kill $sshpid

